name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v4

    - name: Install linux deps
      run: |
        #pacman-contrib is for updpkgsums
        pacman -Syu just namcap pacman-contrib --noconfirm --needed
      
    - name: Test makepkg
      run: just makepkg

    - name: namcap
      run: just namcap
