name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v4

    - name: Install linux deps
      run: |
        # pacman-contrib is for updpkgsums
        pacman -Syu git base-devel sudo just namcap pacman-contrib --noconfirm --needed

    - name: Test makepkg
      # NOTE: makepkg can't run as root so this is the workaround
      run: |
        sudo chown -R nobody:nobody .
        sudo -u nobody just makepkg

    - name: namcap
      run: just namcap
